/* User Authentication state */
export const IS_USER_AUTHENTICATING = 'IS_USER_AUTHENTICATING';
export const IS_USER_AUTHENTICATED = 'IS_USER_AUTHENTICATED';
export const LOAD_USER_SESSION = 'LOAD_USER_SESSION';

// login user
export const LOG_IN_USER_SUCCESS = 'LOG_IN_USER_SUCCESS';
export const LOG_IN_USER_FAILURE = 'LOG_IN_USER_FAILURE';
export const LOG_IN_USER_REQUEST = 'LOG_IN_USER_REQUEST';